# Looking Glass kvmfr default sizing
# 128 MiB is enough for 4K 32bpp single-buffered. Increase for 4K HDR or
# higher resolution by calculating: width * height * 4 * 2 (double-buffered)
# e.g. 3840*2160*4*2 = 64MiB single / 128MiB double.
options kvmfr static_size_mb=128