# CloudWS-OS: Strict USBGuard Daemon Configuration
# https://usbguard.github.io/

RuleFile=/etc/usbguard/rules.conf
RuleFolder=/etc/usbguard/rules.d/

ImplicitPolicyTarget=block
PresentDevicePolicy=allow
PresentControllerPolicy=allow
InsertedDevicePolicy=block
RestoreControllerDeviceState=false
DeviceManagerBackend=uevent
IPCAllowedUsers=root cloudws
IPCAllowedGroups=wheel
DeviceRulesWithPort=false
AuditFilePath=/var/log/usbguard/usbguard-audit.log
