# anaconda.toml
---

# Installable ISO (Anaconda)
[customizations.installer.kickstart]
contents = """
text --non-interactive
lang en_US.UTF-8
keyboard us
timezone --utc UTC
reqpart --add-boot
part / --grow --fstype=ext4
"""

[customizations.installer.modules]
enable  = ["org.fedoraproject.Anaconda.Modules.Storage"]
disable = ["org.fedoraproject.Anaconda.Modules.Users"]

[customizations.iso]
volume_id      = "MIOS"
application_id = "MiOS"
publisher      = "Kabuki94"